### ISSUE TITLE
Error trying to import

### ISSUE THREAD

**Issue by jamiesmith** [setiastro/pixinsight-updates#1]
Hi - the new script looks great!

I added the URL from the [scripts page](https://www.setiastro.com/pjsr-scripts) to my repo list as this:
`https://raw.githubusercontent.com/setiastro/pixinsight-updates/main/`

but when I try to check for updates in PixInsight I run into this error:

```
Repository URL     : https://raw.githubusercontent.com/setiastro/pixinsight-updates/main/
Signature          : <* unavailable *>
Authorized         : false
Available packages : 0
Selected packages  : 0
Error log:
https://raw.githubusercontent.com/setiastro/pixinsight-updates/main/: Parsing repository update information: Parsing Signature element (line=1 offset=0): Unknown code signing identity 'FranklinMarek'
```

Am I missing something in my config?
Thanks!

**Comment by setiastro** [comment]
If you havent upgraded to PixInsight build 1605 (which came out in March) I
highly recommend you do that as all scripts are going to require signatures
going forward. You do this from the PixInsight download site. This will fix
the error if you are trying to use the repository.

If you still run into a parsing error or signature error you can download
the zip file directly from my website and then just extract the .js files
(delete the .xsgn file). You can then go to Scripts -> Feature Scripts ->
Add Script and select the folder you extracted the .js file too.

Let me know if this helps

Frank

**Comment by jamiesmith** [comment]
I think that's it- it worked on one of my machines and I was trying to help one of the guys in my club.

Sorry for the noise- are these repos allowed to have a readme? I'm going to apply for the CDP myself :)

**Comment by jamiesmith** [comment]
Works with newer version

**Comment by setiastro** [comment]
Yes you can have a readme.  The repository is just a zip folder with
scripts folder inside a scr folder.  I wish I wouldve been smart and put a
setiastro folder inside the scripts folder.  The things like readme's would
be easy to find.  If you have all your files just in the scripts folder
that is where pixinsight will put it in the hardrive too.

If yoy need help setting up the .xri text file or fearure id's or anything
let me know.

Frank
